listen: 80
hosts:
  default:
    paths:
      /:
        file.dir: app/public
        mruby.handler-file: app/ruby/handler.rb
        file.dir: content
        file.dir: /tmp/cms

access-log: /dev/stdout
error-log: /dev/stderr
user: root