resources:
  - jpg
  - png
  - svg

excerpt: 2

pandoc:
  md:
    from: markdown_github+footnotes+inline_notes
    to: html5
  rst:
    from: rst
    to: html5

content_dir: content
tmp_dir: /tmp/cms
