- match: ^/env$
  body: |
    #{JSON.generate(env)}

# Entry
-
  match: '^(?<uri>/(?<id>[\w\W\d]{4})/)(?:index.html)?$'
  handler: page.php
  view: index.html
  main: entry.html
  helper: Entry
  local: true

# Archive
-
  match: '^(?<uri>/archives(?:/(?<yyyymm>[1-9][0-9]{4}(?:[1][0-2]|[0][1-9]))/)?)(?:index.html)?$'
  handler: page.php
  view: index.html
  helper: Archive

# Top
-
  match: '^(?<uri>/)(?:index\.html)?$'
  handler: page.php
  view: index.html
  helper: Index
  page: 1

# Paginated Index
-
  match: '^(?<uri>/page/(?<page>[\d]+)/)(?:index\.html)?$'
  handler: page.php
  view: index.html
  helper: Index

-
  match: 'test'
  status: 404

# Directory
-
  match: '^(?<view>(?<uri>(/[^/]+)*/)(?:index\.html))$'
  handler: page.php
  helper: Page

# Index
-
  match: '^(?<view>(?<uri>(/[^/]+)*/[^/]+))$'
  handler: page.php
  helper: Page
  name: Index
