-
  name: Eval
  match: '^/eval(?:/(?<expr>.+))?$'
  body: |
    #{eval(context['expr'])}

-
  name: Forbidden
  match: '(?:\.md|\.yml)$'
  status: 403
  body: forbidden

-
  name: Assets
  match: '(?:\.jpg|\.png|\.svg)$'
  status: 399

-
  name: Css
  match: '\.css$'
  handler: sass.sh
  content_type: text/css; charset=utf-8
  condition: |
    !`find html#{context['uri'].sub(/\.css$/, '.s[ac]ss')}`.empty?

-
  name: Directory
  match: '^(?<view>(?<uri>(/[^/]+)*/)(?:index\.html))$'
  handler: page.php
  condition: |
    File.exists?(File.join('html',context['uri']))

-
  name: Xml
  match: '^(?<view>(?<uri>(/[^/]+)*/[^/]+\.xml))$'
  handler: page.php
  content_type: application/xml; charset=utf-8
  condition: |
    File.exists?(File.join('html',context['uri']))

-
  name: Index
  match: '^(?<view>(?<uri>(/[^/]+)*/[^/]+))$'
  handler: page.php
  condition: |
    File.exists?("html/#{context['uri']}.php")
