-
  match: '^/eval(?:/(?<expr>.+))?$'
  body: |
    #{eval(context['expr'])}

-
  match: '(?:\.md|\.yml)$'
  status: 403
  body: forbidden

# assets
-
  match: '(?:\.jpg|\.png|\.svg)$'
  status: 399

# css
-
  match: '\.css$'
  handler: sass.sh
  content_type: text/css; charset=utf-8
  condition: |
    !`find html#{context['uri'].sub(/\.css$/, '.s[ac]ss')}`.empty?

# Directory
-
  match: '^(?<view>(?<uri>(/[^/]+)*/)(?:index\.html))$'
  handler: page.php
  condition: |
    File.exists?(File.join('html',context['uri']))

# Xml
-
  match: '^(?<view>(?<uri>(/[^/]+)*/[^/]+\.xml))$'
  handler: page.php
  content_type: application/xml; charset=utf-8
  condition: |
    File.exists?(File.join('html',context['uri']))

# Index
-
  match: '^(?<view>(?<uri>(/[^/]+)*/[^/]+))$'
  handler: page.php
  condition: |
    File.exists?(File.join('html',context['uri']))
