-
  match: ^(?<uri>/(?<id>[\w\W\d]{4})/)(?:index.html)?$
  handler: page.php
  view: views/main.html
  helper: Entry
  index: index.html

-
  match: archives(/(?<yyyymm>[1-9][0-9]{4}([1][0-2]|[0][1-9])))?
  handler: page.php
  view: views/archive.html
  helper: Archive
  index: index.html

# トップページ
-
  match: ^(?<uri>/)(?:index\.html)?$
  handler: page.php
  view: views/main.html
  helper: Index
  page: 1
  index: index.html

# ページ送り
-
  match: ^(?<uri>/page/(?<page>[\d]+)/)(?:index\.html)?$
  handler: page.php
  view: views/main.html
  helper: Index
  index: index.html

-
  match: ^/sitemap.xml$
  handler: page.php
  view: views/sitemap.xml
  helper: Page
