-
  match: ^(?<uri>/(?<id>[\w\W\d]{4})/)(?:index.html)?$
  view: web/html/main.html
  class: Entry
  handler: page.php
  index: index.html

-
  match: archives(/(?<yyyymm>[1-9][0-9]{4}([1][0-2]|[0][1-9])))?
  view: web/html/archive.html
  class: Archive
  handler: page.php
  index: index.html

# トップページ
-
  match: ^(?<uri>/)(?:index\.html)?$
  view: web/html/main.html
  class: Index
  page: 1
  handler: page.php
  index: index.html

# ページ送り
-
  match: ^(?<uri>/page/(?<page>[\d]+)/)(?:index\.html)?$
  view: web/html/main.html
  class: Index
  handler: page.php
  index: index.html

-
  match: ^/sitemap.xml$
  view: web/html/sitemap.xml
  class: Page
  handler: page.php
